language: node_js
node_js: node
script:
  - npm test
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 8330......4274
    secure: LIClNxJYURoHCUSa+felRWo9HnqCRhiyhujPcLvz5/K0nawQuQQP+v1QQ4mpdfn/mxDQnGIqARi94XwfZPfu0wJGxXk1aATpkkdqUisNL2TiJCZV6OKooTggSuK5hu0YjvG0s3SQAQJRV9nkYi1fYmJR2GXJWaD0Uph+6haTxRHwnSLNLjtW8DDCKkxIXvbFUS7rw4AuQcq2xNqQcJyTcVjOnotSUuQrNzaWejnXnQ3JrVqQvXaVDLjYFt+OOg68qWrJSU1fQH88vV7hdZwmvqcbYaqHCGpsnQbfaaZMXUW4gHWOXiOkSEYnRg46mVAslN4PljGNITxcPYIWG2RkpI/da9HT5HKWz0dwUGgFFwckJd1JhedIldmh6aoJWdSJQoE3Inm1MMHFT0cslcFsk6KQsAHrO0xqs6Aa3CpxyBpcYaqeXSp6EYm0ooM15l7dl3sInT8sB//+DwH9GfBs5w0nWkYyAXcZsWd/UITbnsGEQyheu1/6+koP+lRSjdrzfz4tS9Y/15NjnvKPm5io0JpyNNvwI5pyj82inoIc3Kif7Jk3HbA7x9dua78iFKF8YmAbNJm1AGgSfWOhFz9+8lEa8a0NE1OWRSNYGTgcnl9ZDad2hciswJzIKrFn3LP5READB8abujjTPO2UFVNQuxpHkiGWOQkpFLhoPAlqPog=
  on:
    tags: true
    repo: Brightspace/d2l-beaker
    all_branches: true
